// regions
export const GET_REGIONS_LIST = 'GET_REGIONS_LIST';
export const ADD_REGION = 'ADD_REGION';
export const DELETE_REGION = 'DELETE_REGION';
export const GET_ALL_COUNTRY = 'GET_ALL_COUNTRY';
export const GET_ALL_ADMIN = 'GET_ALL_ADMIN';
export const DELETE_COUNTRY = 'DELETE_COUNTRY';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const DELETE_ADMIN = 'DELETE_ADMIN';
export const ADD_ADMIN = 'ADD_ADMIN';

// modles
export const GET_MODELS_LIST = 'GET_MODELS_LIST';
export const ADD_MODEL = 'ADD_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_MODELS = 'ADD_MODELS';
export const DELETE_MODELS = 'DELETE_MODELS';

//labels
export const GET_LABELS = 'GET_LABELS';
export const ADD_LABELS = 'ADD_LABELS';
export const DELETE_LABELS = 'DELETE_LABELS';
//FAQ
export const GET_CATEGORYS = 'GET_CATEGORYS';
export const SEARCH_FAQ = 'SEARCH_FAQ';
export const CHANGE_FAQ_DISPLAY = 'CHANGE_FAQ_DISPLAY';





export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST';
export const GET_CHART_DATA_SUCCESS = 'GET_CHART_DATA_SUCCESS';
export const GET_CHART_DATA_FAILURE = 'GET_CHART_DATA_FAILURE';

export const CLICK_TEST = 'CLICK_TEST';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const ADD_RANDOM_USER = 'ADD_RANDOM_USER';

export const SUBMIT_CONFIG_REQUEST = 'SUBMIT_CONFIG_REQUEST';
export const SUBMIT_CONFIG_SUCCESS = 'SUBMIT_CONFIG_SUCCESS';
export const SUBMIT_CONFIG_FAILURE = 'SUBMIT_CONFIG_FAILURE';

//���¹���ҳ���action����name
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_FETCH_TYPE = 'GET_FETCH_TYPE';
export const CHANGE_FETCH_TYPE = 'CHANGE_FETCH_TYPE';

export const GET_SOURCE_OPTION = 'GET_SOURCE_OPTION';
export const CHANGE_SOURCE_OPTION = 'CHANGE_SOURCE_OPTION';
export const CHANGE_TIME_TYPE = 'CHANGE_TIME_TYPE';
export const SET_TIME_FROM = 'SET_TIME_FROM';
export const SET_TIME_TO = 'SET_TIME_TO';
export const GET_ALL_PUSH = 'GET_ALL_PUSH';
export const SET_KEYWORD = 'SET_KEYWORD';
export const QUERY_NEWS = 'QUERY_NEWS';
export const CHANGE_FILTER_TYPE = 'CHANGE_FILTER_TYPE';
export const PUSH_AND_UNPUBLISH = 'PUSH_AND_UNPUBLISH';
export const GET_CONTENT = 'GET_CONTENT';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const RECOMMEND = 'RECOMMEND';
export const STICKY = 'STICKY';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const CREATE_ARTILE = 'CREATE_ARTILE';
export const SET_HEAD_PIC = 'SET_HEAD_PIC';
export const GET_COMMENTS = 'GET_COMMENTS';
export const BLOCK_COMMENT = 'BLOCK_COMMENT';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const GET_TAGS = 'GET_TAGS';
export const CHANGE_ORDER = 'CHANGE_ORDER';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_ALL_SOURCE = 'GET_ALL_SOURCE';
export const GET_SOURCE_LIST = 'GET_SOURCE_LIST';
export const SET_SWITCH = 'SET_SWITCH';
export const DELETE_TAG = 'DELETE_TAG';
export const GET_APP_LIST = 'GET_APP_LIST';
export const MODIFY_APK = 'MODIFY_APK';
export const LOADING = 'LOADING';
export const MODIFY_CATEGORY = 'MODIFY_CATEGORY';
export const DELETE_APK = 'DELETE_APK';
export const PUSH_THIS_ARTICLE = 'PUSH_THIS_ARTICLE';


